version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    networks:
      - database

  rest-gateway:
    build:
      dockerfile: Dockerfile.local
    container_name: rest-gateway
    command: gin -i --build $REST_DIR --bin $REST_DIR/gin-bin run
    depends_on:
      - inventory-api
      - session-api
    networks:
      - backend
    ports:
      - $REST_PORT:3001
    environment:
      OTEL_SERVICE_NAME: $REST_DIR
    volumes:
      - .:/app

  graphql-gateway:
    build:
      dockerfile: Dockerfile.local
    container_name: graphql-gateway
    command: gin -i --build $GRAPHQL_DIR --bin $GRAPHQL_DIR/gin-bin run
    depends_on:
      - inventory-api
      - session-api
    networks:
      - backend
    ports:
      - $GRAPHQL_PORT:3001
    environment:
      OTEL_SERVICE_NAME: $GRAPHQL_DIR
    volumes:
      - .:/app

  inventory-api:
    build:
      dockerfile: Dockerfile.local
    container_name: inventory-api
    command: gin -i --build $INVENTORY_DIR --bin $INVENTORY_DIR/gin-bin -a $PORT run
    depends_on:
      - mongo
    networks:
      - backend
      - database
    environment:
      OTEL_SERVICE_NAME: $INVENTORY_DIR
    volumes:
      - .:/app

  session-api:
    build:
      dockerfile: Dockerfile.local
    container_name: session-api
    command: gin -i --build $SESSION_DIR --bin $SESSION_DIR/gin-bin -a $PORT run
    depends_on:
      - mongo
    networks:
      - backend
      - database
    environment:
      OTEL_SERVICE_NAME: $SESSION_DIR
    volumes:
      - .:/app

networks:
  backend:
    driver: bridge
  database:
    driver: bridge
